### ISSUE TITLE
点击反应等待太久

### ISSUE THREAD

**Issue by zyyv** [elonehoo/vue-decolorization#1]
很不错的项目😄
玩了一下，发现后面的点击响应时间太慢了，2s左右的响应等待时间（level 5）。

<img width="572" alt="image" src="https://user-images.githubusercontent.com/42139754/163204100-8edd30fd-b330-4581-9bf9-2658f5a44bf4.png">

**Comment by elonehoo** [comment]
是有这个问题，还没想好咋优化……

**Comment by elonehoo** [comment]
明天考虑一下

**Comment by elonehoo** [comment]
或者大佬帮帮忙

**Comment by zyyv** [comment]
> 或者大佬帮帮忙

哈哈哈，有意思的项目，明天看看源码  有空就提pr
